# Generated by Django 6.0.7 on 2026-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
